server:
  port: 6004

spring:
  application:
    name: hystrix-consumer

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka


#hystrix:
#  command:
#     default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
feign:
  hystrix:
    enabled: true
#  client:
#    config:
#      remote-service:
#        connectTimeout: 5000
#        readTimeout: 5000
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: ture
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms
#
#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000

#CLOUD-PROVIDER-HYSTRIX-PAYMENT:
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000




