server:
  port: 9003
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8999
      eager: true

service:
  name: nacos-payment-provider

feign:
  sentinel:
    enabled: true
