server:
  port: 2001
spring:
  application:
    name: seata-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: suntek
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8999
      eager: true
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
    alibaba:
      seata:
        tx-service-group: orderService

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml

seata:
  storage: seate-storage-service
  account: seate-account-service

feign:
#  client:
#    config:
##      default:
##        connectTimeout: 100000
##        readTimeout: 100000
#      testTimeOut:
#        connectTimeout: 5000
#        readTimeout: 5000
  sentinel:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

