server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer8803
  cloud:
    stream:
      binders: #配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名字，用于与bingding整和
          type: rabbit
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的exchange名称的定义
          content-type: application/json
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: cctv1

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    instance-id: get8803.com
    prefer-ip-address: true